### PR TITLE
Account for complex sector types

### PR DESCRIPTION
**Pull request by mhauru**

### CODE REVIEW

**Comment by Jutho** [comment]
I don't understand this one (but have not looked at the full code in detail). Why does the real vs complex of the topological data of the sector affect this?

**Comment by Jutho** [comment]
Ah now I understand, I don't allow to create tensors with real-valued data if the sectortype is complex. All of this should be changed by introducing a `DiagonalTensorMap` type, which could be real-valued even for complex sectortype

**Comment by mhauru** [comment]
Yes, that is indeed the point.

**Comment by Jutho** [comment]
Ok I'll merge like this, and then we should revisit this if `DiagonalTensorMap` arrives.

**Pull request merged**
